name: Dependent workflow

on:
  workflow_run:
    workflows: ["Manual or Release triggered"]
    #branches: [main]
    types: 
      - completed

jobs:

  success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Success
      run: |
        echo "Success!"

  not-success:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Not Success
      run: |
        echo "Not Success :("
