name: Dependent workflow

on:
  workflow_run:
    workflows: ["Manual or Release triggered"]
    branches:
      - main
      - 'v[0-9]+.[0-9]+.[0-9]+(-[a-zA-Z0-9]+)?'
    types: 
      - completed

jobs:

  success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Success
      run: |
        echo "Success!"
        printenv

  not-success:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Not Success
      run: |
        echo "Not Success :("
        printenv
